vich_uploader:
    db_driver: orm
    mappings:
        animal_images:
            uri_prefix: /uploads/animals
            upload_destination: '%kernel.project_dir%/public/uploads/animals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
